// Promenade
//////////////

IF
   Global("ExnemSpawnItem","AR0700",0)
THEN
   RESPONSE #100
      SetGlobal("ExnemSpawnItem","AR0700",1)
      ActionOverride("Chest 2",CreateItem("SCRXX06",0,0,0) // 
      ActionOverride("Chest 2",CreateItem("RNDTRE05",0,0,0) // 
      ActionOverride("Table 14",CreateItem("SCRXX01",0,0,0) // 
      ActionOverride("Table 4",CreateItem("SCRXX25",0,0,0) // 
      ActionOverride("Table 9",CreateItem("RNDTRE04",0,0,0) // 
      Continue()
END
