// Hell, Beholder area
//////////////

IF
   Global("ExnemSpawnItem","AR2901",0)
THEN
   RESPONSE #100
      SetGlobal("ExnemSpawnItem","AR2901",1)
      ActionOverride("Container 1",CreateItem("SCRXX02",0,0,0) // 
      ActionOverride("Container 1",CreateItem("SCRXX03",0,0,0) // 
      ActionOverride("Container 1",CreateItem("SCRXX08",0,0,0) // 
      ActionOverride("Container 1",CreateItem("XSWD006",0,0,0) // 
      Continue()
END
